//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectionHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> ExportTime { get; set; }
        public string Status { get; set; }
        public string Messages { get; set; }
        public string CaseName { get; set; }
        public string LogType { get; set; }
        public string InterceptId { get; set; }
        public string InterceptName { get; set; }
    }
}
