//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncGUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallReExport
    {
        public int Id { get; set; }
        public string Casename { get; set; }
        public string InterceptName { get; set; }
        public string InterceptId { get; set; }
        public string ElasticId { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string WriteTime { get; set; }
        public string Type { get; set; }
    }
}
